# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

APPLY_FIXES: all
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

DISABLE:
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY

JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_STANDARD_FILTER_REGEX_INCLUDE: (src\|vite\.config\.ts)
